services:
  - type: web
    name: pharmatrack
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install email-validator && pip install -r requirements.txt"
    startCommand: "bash start.sh"
    healthCheckPath: "/docs"
    envVars:
      - key: ADMIN_EMAIL
        value: sailendrabramham2003@yahoo.com
      - key: EMAIL_FROM
        value: voldemortvoledemort@gmail.com
      - key: EMAIL_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./pharmacy.db
      - key: PYTHON_VERSION
        value: 3.11.0
